C ssg
#define MPI_BCAST(BUFFER,CNT,DATATYPE,ROOT,COMM,IERR) MPI_NOOP()
#define MPI_SEND(BUF,CNT,DATATYPE,DEST,TAG,COMM,IERR) MPI_NOOP()
#define MPI_RECV(BUF,CNT,DTYPE,SOURCE,TAG,COMM,STATUS,IERR) MPI_NOOP()
#define MPI_ISEND(BUF,CNT,DATATYPE,DEST,TAG,COMM,IREQ,IERR) MPI_NOOP()
#define MPI_UNPACK(INBUF,INSIZE,POSITION,OUTBUF,OUTCNT,DATATYPE,COMM,IERR) MPI_NOOP()
#define MPI_PACK(INBUF,INCNT,DATATYPE,OUTBUF,OUTCNT,POSITION,COMM,IERR) MPI_NOOP()
