// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __rmumps_h__
#define __rmumps_h__

#include "rmumps_RcppExports.h"

#endif // __rmumps_h__
