// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rmumps.h"
#include <Rcpp.h>

using namespace Rcpp;

// get_cnst
int get_cnst(std::string s);
RcppExport SEXP _rmumps_get_cnst(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(get_cnst(s));
    return rcpp_result_gen;
END_RCPP
}
