# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' get value of a c++ macro constant
#'
#' Return an integer number defined as c++ macro if it is present in internal dictionary. The input parameter is the name of the constant to be returned. If the name is not found in the dictionary, an error is thrown. Constants currently present in the dictionary are following: RMUMPS_PERM_AMD, RMUMPS_PERM_AMF, RMUMPS_PERM_SCOTCH, RMUMPS_PERM_PORD, RMUMPS_PERM_METIS, RMUMPS_PERM_QAMD and RMUMPS_PERM_AUTO.
#' 
#' @param s character scalar, name of the constant
#' @return integer scalar, value of the sonstant
#' @aliases RMUMPS_PERM_AMD RMUMPS_PERM_AMF RMUMPS_PERM_SCOTCH RMUMPS_PERM_PORD RMUMPS_PERM_METIS RMUMPS_PERM_QAMD RMUMPS_PERM_AUTO
#' @examples
#' get_cnst("RMUMPS_PERM_AMD")
#' @export
get_cnst <- function(s) {
    .Call('_rmumps_get_cnst', PACKAGE = 'rmumps', s)
}

